### ISSUE TITLE
几个xss以及一些别的

### ISSUE THREAD

**Issue by kevinocalm** [nsmaomao/mao10cms#1]
![mao10cms-xss-0](https://cloud.githubusercontent.com/assets/13563369/16827156/675b88a4-49b6-11e6-9863-e09fa1b9684f.png)
![mao10cms-xss-1](https://cloud.githubusercontent.com/assets/13563369/16827155/674c532a-49b6-11e6-94e8-950ab2c550d1.png)
![mao10cms-xss-2](https://cloud.githubusercontent.com/assets/13563369/16827154/673ed56a-49b6-11e6-8b3d-a248cd10e060.png)
![mao10cms-xss-3](https://cloud.githubusercontent.com/assets/13563369/16827153/67388700-49b6-11e6-842a-5849cd8f5a1d.png)
不止这些，细节一点的东西邮件（kevinoclam@126.com）联系吧....直接放在这里不太好

**Comment by nsmaomao** [comment]
好滴，感谢
